name: Build and Deploy of StarKnight

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Game
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: StarKnight

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cache Library folder
      - name: Cache Library folder
        uses: actions/cache@v2
        with:
          path: path/to/your/project/Library
          key: Library-MyProjectName-TargetPlatform
          restore-keys: |
            Library-MyProjectName-
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Upload
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

  deploy:
    name: Deploy to itch.io
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: Build
          path: build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: itch-io
          folder: build/WebGL

      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: StarKnight
          ITCH_USER: Surveiior
          BRANCH: itch-io
          PACKAGE: build/WebGL
