name: Build and Deploy of StarKnight

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Game
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: StarKnight

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project as Unity WebGL
        uses: game-ci/unity-builder@v2
        with:
          target-platform: WebGL
          unity-version: 2021.3.25f1
          project-path: StarKnight
          build-name: WebGL
          build-path: StarKnight/dist
          build-script: BuildScript.BuildWebGL
          extra-args: --no-cache
          
  deploy:
    name: Deploy to itch.io
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to itch.io
        uses: game-ci/itchio-deploy@v1
        with:
          api-key: ${{ secrets.ITCH_API_KEY }}
          project-name: StarKnight
          channel-name: HTML5
          build-path: StarKnight/dist